/*
program description:
	using PID and motorSync, robot will move forward forward straight untill a black line is met, 
	where it will then stop moving. Once it detects a ligh surface, it will continue moving until
	a dark line is met again. The program does not end unless the user presses the center button.
author: renee low
*/

#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colourSensor,   sensorEV3_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	while(getButtonPress(buttonEnter) == 0){
		displayTextLine(5, "press enter to end");
		
		// stops moving when a black line is detected
		if (SensorValue(colourSensor) < 25){
			setMotorSync(leftMotor, rightMotor, 0, 0);
			sleep(100);
		}
		// continues to move once it detects lighter colour
		else {
			setMotorSync(leftMotor, rightMotor, 0, 20);
		}
	}
}
