/*
program description: 
	using the up,down,left and right buttons, users will be able to select the length of the perimeter the 			robot will make when it runs.
		up for a perimeter of 20cm
		down  for a perimeter of 60cm
		left  for a perimeter of 80cm
		right  for a perimeter of 40cm
author: renee low
*/

#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colourSensor,   sensorEV3_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// function signatures
int findDistance();
void turn90();
void reset();
void drive(int dist, int power);
void gyroSquare(int dist);


task main() {
	int distance;
	
	// brings you to the distance selection
	distance = findDistance();
	// calls the function that makes the square. Passes parameter of the chosen distance.
	gyroSquare(distance);
}

// finds distance
int findDistance() {
	int dist = 0;
	
	//if enter button is not pressed
	while(getButtonPress(buttonEnter) == 0) {
		displayTextLine(5, "Your distance is %d", dist);
		
		// choice of distances
		if (getButtonPress(buttonUp)) {
			dist = 20;
		}
		else if (getButtonPress(buttonRight)) {
			dist = 40;
		}
		else if (getButtonPress(buttonDown)) {
			dist = 60;
		}
		else if (getButtonPress(buttonLeft)) {
			dist = 80;
		}
	}
	
	return dist;
}

void turn90() {
	resetGyro(gyroSensor);
	
	// makes the robot turn 90 degs
	while(SensorValue[gyroSensor] < 85) {
		setMotorSync(leftMotor, rightMotor, 42, 30);
	}
}

void reset() {
	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);
}

void drive(int dist, int power) {
	//finds the number of rotations to reach the distance
	float rotations = 360*(dist/17.27);
	
	reset();
	// makes the robot move until the distance has been reached
	setMotorSyncEncoder(leftMotor, rightMotor, 0, rotations, 25);
	waitUntilMotorStop(leftMotor);
}

// function makes the robot go in a square
void gyroSquare(int dist) {
	// goes at 25% power
	drive(dist,25);
	turn90();
	
	drive(dist,25);
	turn90();
	
	drive(dist,25);
	turn90();
	
	drive(dist,25);
	turn90();
	
}
	
