/*
program description:
	program implements the following functions. The program also testa each of the function with noPID
		a. void turn90degreesLeft()
		b. void turn90degreesRight()
		c. void goForward1second()
		d. void swingRight90degrees()
		e. void swingLeft90degrees()
		f. void reverse1second()
author: renee low
*/
		
#pragma config(Motor,  motorA,           ,             tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor,  motorD,           ,             tmotorEV3_Large, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// function signatures
void turn90degreesLeft();
void turn90degreesRight();
void goForward1second();
void swingRight90degrees();
void swingLeft90degrees();
void reverse1second();
void pause();

task main()
{
	// calls the desired functions so the robot moves
	turn90degreesLeft();
	turn90degreesRight();
	goForward1second();
	swingRight90degrees();
	swingLeft90degrees();
	reverse1second();
}

void turn90degreesLeft(){
	// turn 90 degrees left
	setMotorSpeed(leftMotor,50); // controls left motor, speed
	setMotorSpeed(rightMotor,0); // controls righ motor, speed
	sleep(980); // how long the action lasts

	pause(); // robot stops moving for a bit before next function runs
}

void turn90degreesRight(){
	// turn 90 degrees right
	setMotorSpeed(leftMotor,0);
	setMotorSpeed(rightMotor,50);
	sleep(980);

	pause();
}

void goForward1second(){
	// goes forward 1s
	setMotorSpeed(leftMotor,50);
	setMotorSpeed(rightMotor,50);
	sleep(1000);

	pause();
}

void swingRight90degrees(){
	// swing right 90 degrees
	setMotorSpeed(leftMotor,0);
	setMotorSpeed(rightMotor,100);
	sleep(955);

	pause();
}

void swingLeft90degrees(){
	// swing left 90 degrees
	setMotorSpeed(leftMotor,100);
	setMotorSpeed(rightMotor,0);
	sleep(955);
}

void reverse1second(){
	// reverse 1s
	setMotorSpeed(leftMotor,-50);
	setMotorSpeed(rightMotor,-50);
	sleep(1000);
}

void pause(){
	// pause .5s
	setMotorSpeed(leftMotor,0);
	setMotorSpeed(rightMotor,0);
	sleep(500);
}
