#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,           ,             tmotorEV3_Large, openLoop)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*/

// function signatures
void pause(int);
void drive(long, long, long);
void turn90(long, long);

task main()
{
	// randomly generates which way the robot turns
	int turn = 0;
	int direction = random(1);
	if (direction == 1) {
		turn = 50; // right
	}
	else {
		turn = -50; // left
	}
	
	//calling functions to make a square
	drive(0, 240, 100); // 240 = distance
	turn90(turn, 50); // 2nd num, at ~100, turns 180deg. ~50 for 90deg // 1st num, at 50/-50, turns right/left	
	pause(1000);
	
	drive(0, 240, 100); // 240 = distance
	turn90(turn, 50); 
	pause(1000);
	
	drive(0, 240, 100); // 240 = distance
	turn90(turn, 50); 
	pause(1000);
	
	drive(0, 240, 100); // 240 = distance
	turn90(turn, 50); 
	pause(1000);
}

//function for pausing
void pause(int len) {
	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
	sleep(len);
}


//funtion that moves robot forward
void drive(long nMotorRatio, long dist, long power)
{
	//long degreesToTurn = 0;
	// circum = 17.27cm

	float rotations = 360 * (dist / 17.27);

	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);

	//degreesToTurn = distanceToDegrees(dist);
	setMotorSyncEncoder(leftMotor, rightMotor, 0, rotations, power);
	waitUntilMotorStop(leftMotor);
}


//function to turn // 
void turn90(long nMotorRatio, long turnPow){
	setMotorSyncTime(leftMotor, rightMotor, turnPow, 1000, nMotorRatio);
	sleep(1500);
}
